name = "LearnLean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LearnLean"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "proofwidgets"
git = "https://github.com/leanprover-community/ProofWidgets4"
rev = "v0.0.46"

[[require]]
name = "scilean"
git = "https://github.com/lecopivo/SciLean"

[[lean_lib]]
name = "LearnLean"
